package com.schappet.c4.clubRoster.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.c4.clubRoster.domain.*;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 04/21/2016 20:21:12 CDT
 */
public interface ClubMemberService extends GenericDaoInterface<ClubMember> {

	public ClubMember findById( Integer id );

}