package com.schappet.c4.clubRoster.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.c4.clubRoster.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 04/21/2016 20:21:12 CDT
 */
@Transactional
@Repository( "com_schappet_c4_clubRoster_dao_MemberGearHome" )
public class MemberGearHome extends GenericDao<MemberGear> implements MemberGearService {

	public MemberGearHome() {
		setDomainName( "com.schappet.c4.clubRoster.domain.MemberGear" );
	}

	public MemberGear findById( Integer id ) {
		return (MemberGear) this.sessionFactory.getCurrentSession().get( MemberGear.class, id );
	}

}