package com.schappet.c4.clubRoster.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import com.schappet.c4.clubRoster.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 04/21/2016 20:21:12 CDT
 */
@Controller( value = "com_schappet_c4_clubRoster_controller_clubmember_controller" )
@RequestMapping( "/clubmember" )
public class ClubMemberController extends AbstractClubRosterController {

    private static final Log log = LogFactory.getLog( ClubMemberController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "clubMemberList", clubRosterDaoService.getClubMemberService().list() );
        return "/clubroster/clubmember/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list(Model model) {
    	// needed for AngularJS grid/CRUD functionality
    	 
        return "/clubroster/clubmember/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = clubRosterDaoService.getClubMemberService().count( options );
            List<ClubMember> clubMemberList = clubRosterDaoService.getClubMemberService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( ClubMember clubMember : clubMemberList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "memberId" :
							tableRow.put( dataName, clubMember.getMemberId() );
							break;
						case "username" :
							tableRow.put( dataName, clubMember.getUsername() );
							break;
						case "firstName" :
							tableRow.put( dataName, clubMember.getFirstName() );
							break;
						case "lastName" :
							tableRow.put( dataName, clubMember.getLastName() );
							break;
						case "emailAddress" :
							tableRow.put( dataName, clubMember.getEmailAddress() );
							break;
						case "password" :
							tableRow.put( dataName, clubMember.getPassword() );
							break;
						case "memberCode" :
							tableRow.put( dataName, clubMember.getMemberCode() );
							break;
						case "memberSince" :
							tableRow.put( dataName, clubMember.getMemberSince() );
							break;
						case "isGuest" :
							tableRow.put( dataName, clubMember.getIsGuest() );
							break;
						case "memberGears" :
							tableRow.put( dataName, clubMember.getMemberGears().size() );
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/clubmember/show?"+"memberId="+clubMember.getMemberId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/clubmember/edit?"+"memberId="+clubMember.getMemberId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/clubmember/delete?"+"memberId="+clubMember.getMemberId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for ClubMember", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "clubMember", new ClubMember() );

        return "/clubroster/clubmember/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "memberId" ) Integer clubMemberId ) {


        model.addAttribute( "clubMember", clubRosterDaoService.getClubMemberService().findById( clubMemberId ) );
        return "/clubroster/clubmember/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "memberId" ) Integer clubMemberId ) {

        model.addAttribute( "clubMember", clubRosterDaoService.getClubMemberService().findById( clubMemberId ) );
        return "/clubroster/clubmember/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "clubMember" ) ClubMember clubMember, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
			
			return "/clubroster/clubmember/edit"; 
		} else {
			try {
				clubRosterDaoService.getClubMemberService().saveOrUpdate( clubMember );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				clubRosterDaoService.getClubMemberService().merge( clubMember );
			}
		}
		return "redirect:/clubmember/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "memberId" ) Integer clubMemberId ) {

        model.addAttribute( "clubMember", clubRosterDaoService.getClubMemberService().findById( clubMemberId ) );
        return "/clubroster/clubmember/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "memberId" ) Integer clubMemberId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            clubRosterDaoService.getClubMemberService().delete( clubRosterDaoService.getClubMemberService().findById( clubMemberId ) );
        }
        return "redirect:/clubmember/list";
    }
}