package com.schappet.c4.clubRoster.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import com.schappet.c4.clubRoster.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 04/21/2016 20:21:13 CDT
 */
@Controller( value = "com_schappet_c4_clubRoster_controller_membergear_controller" )
@RequestMapping( "/membergear" )
public class MemberGearController extends AbstractClubRosterController {

    private static final Log log = LogFactory.getLog( MemberGearController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "memberGearList", clubRosterDaoService.getMemberGearService().list() );
        return "/clubroster/membergear/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list(Model model) {
    	// needed for AngularJS grid/CRUD functionality
    			model.addAttribute( "gearList", clubRosterDaoService.getGearService().list() );
		model.addAttribute( "clubMemberList", clubRosterDaoService.getClubMemberService().list() );
 
        return "/clubroster/membergear/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = clubRosterDaoService.getMemberGearService().count( options );
            List<MemberGear> memberGearList = clubRosterDaoService.getMemberGearService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( MemberGear memberGear : memberGearList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "memberGearId" :
							tableRow.put( dataName, memberGear.getMemberGearId() );
							break;
						case "gear" :
							if( memberGear.getGear() != null ){
								tableRow.put( dataName, memberGear.getGear().toString() );
							}
							break;
						case "clubMember" :
							if( memberGear.getClubMember() != null ){
								tableRow.put( dataName, memberGear.getClubMember().toString() );
							}
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/membergear/show?"+"memberGearId="+memberGear.getMemberGearId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/membergear/edit?"+"memberGearId="+memberGear.getMemberGearId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/membergear/delete?"+"memberGearId="+memberGear.getMemberGearId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for MemberGear", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "memberGear", new MemberGear() );
		model.addAttribute( "gearList", clubRosterDaoService.getGearService().list() );
		model.addAttribute( "clubMemberList", clubRosterDaoService.getClubMemberService().list() );

        return "/clubroster/membergear/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "memberGearId" ) Integer memberGearId ) {
		model.addAttribute( "gearList", clubRosterDaoService.getGearService().list() );
		model.addAttribute( "clubMemberList", clubRosterDaoService.getClubMemberService().list() );


        model.addAttribute( "memberGear", clubRosterDaoService.getMemberGearService().findById( memberGearId ) );
        return "/clubroster/membergear/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "memberGearId" ) Integer memberGearId ) {

        model.addAttribute( "memberGear", clubRosterDaoService.getMemberGearService().findById( memberGearId ) );
        return "/clubroster/membergear/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "memberGear" ) MemberGear memberGear, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
					model.addAttribute( "gearList", clubRosterDaoService.getGearService().list() );
		model.addAttribute( "clubMemberList", clubRosterDaoService.getClubMemberService().list() );

			return "/clubroster/membergear/edit"; 
		} else {
			try {
				clubRosterDaoService.getMemberGearService().saveOrUpdate( memberGear );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				clubRosterDaoService.getMemberGearService().merge( memberGear );
			}
		}
		return "redirect:/membergear/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "memberGearId" ) Integer memberGearId ) {

        model.addAttribute( "memberGear", clubRosterDaoService.getMemberGearService().findById( memberGearId ) );
        return "/clubroster/membergear/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "memberGearId" ) Integer memberGearId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            clubRosterDaoService.getMemberGearService().delete( clubRosterDaoService.getMemberGearService().findById( memberGearId ) );
        }
        return "redirect:/membergear/list";
    }
}