package com.schappet.c4.clubRoster.resouce;




import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.junit.Assert.assertEquals;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.schappet.c4.clubRoster.controller.AbstractControllerMVCTests;
import com.schappet.c4.clubRoster.domain.ClubMember;

/**
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since Sat Apr 23 10:55:33 CDT 2016
 */
public class ClubMemberResourceMvcTest extends AbstractControllerMVCTests {
	
    private ClubMember firstClubMember;
    private ObjectMapper mapper;
    
    @Before
    public void before() { 
        // add 20 records to test database
        for(int x=1; x<21; x++){
        	ClubMember clubMember = new ClubMember();
        	clubRosterDaoService.getClubMemberService().save(clubMember);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstClubMember = clubMember;
	        }
        }   
        this.mapper = new ObjectMapper();
        // fix NonUniqueObjectException
        this.clubRosterDaoService.getClubMemberService().getSession().flush();
        this.clubRosterDaoService.getClubMemberService().getSession().clear();
    }    
      
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void getByPathVariableIdShouldLoadAndReturnObject() throws Exception {
    	mockMvc.perform(get("/rest/clubmember/"+firstClubMember.getMemberId().toString()))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.memberId", is(firstClubMember.getMemberId())))
        ;
    }
  
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void getByPathVariableIdShouldReturn404ForBogusId() throws Exception {
    	mockMvc.perform(get("/rest/clubmember/-123")).andExpect(status().isNotFound()).andExpect(jsonPath("$.message", is("/rest/clubmember/-123 could not be found.")));
    }
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void restMappingNotFoundShouldReturn404() throws Exception {
    	mockMvc.perform(get("/rest/clubmember/asdfasdf/asdfasdf"))
    	.andExpect(status().isNotFound())
    	 .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.message", is("/rest/clubmember/asdfasdf/asdfasdf could not be found.")))
    	;
    }
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void createShouldPersistAndReturnObject() throws Exception {
	   long count = clubRosterDaoService.getClubMemberService().count();	       
	   ClubMember clubMember = new ClubMember(); 
       
       mockMvc.perform(post("/rest/clubmember/").content(this.mapper.writeValueAsString(clubMember))
	   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
	   .with(csrf()))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.memberId").value(IsNull.notNullValue()))  
       ;
       
       assertEquals("count should increase by 1", count +1 , clubRosterDaoService.getClubMemberService().count());
	}
     
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void updateShouldPersistExistingAndReturnObject() throws Exception {
       long count = clubRosterDaoService.getClubMemberService().count();

       mockMvc.perform(post("/rest/clubmember/"+ firstClubMember.getMemberId().toString())
    		   .content(this.mapper.writeValueAsString(firstClubMember))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.memberId", is(firstClubMember.getMemberId())))
       ;
         
       assertEquals("count NOT should increase", count , clubRosterDaoService.getClubMemberService().count());
  	}  
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void updateByPathVariableIdShouldReturn404ForMismatchBetweenPathIdAndObjectId() throws Exception {	       
       String correctId =  firstClubMember.getMemberId().toString();
       // this ID manipulation should be overwritten with path variable id
       firstClubMember.setMemberId(-123);
       
       mockMvc.perform(post("/rest/clubmember/"+correctId)
    		   .content(this.mapper.writeValueAsString(firstClubMember))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("/rest/clubmember/" +correctId +" could not be found.")))
       ;
  	} 
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void updateByPathVariableIdShouldReturn404ForBogusPathId() throws Exception {
    	mockMvc.perform(post("/rest/clubmember/-123")
    			.content(this.mapper.writeValueAsString(firstClubMember))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
    	.andExpect(status().isNotFound())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	    .andExpect(jsonPath("$.message", is("/rest/clubmember/-123 could not be found.")));
    }
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void deleteShouldDeleteAndReturnStatusOk() throws Exception {
        long count = clubRosterDaoService.getClubMemberService().count();

        mockMvc.perform(delete("/rest/clubmember/"+ firstClubMember.getMemberId().toString()).with(csrf()))
       .andExpect(status().isOk());  
       
       assertEquals("count should decrease by 1", count - 1 , clubRosterDaoService.getClubMemberService().count());
    }
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void deleteShouldFailWithBogusId() throws Exception {
        long count = clubRosterDaoService.getClubMemberService().count();

        mockMvc.perform(delete("/rest/clubmember/-123").with(csrf()))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("/rest/clubmember/-123 could not be found.")));  
       
       assertEquals("count should NOT decrease by 1", count , clubRosterDaoService.getClubMemberService().count());
    }

    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void listShouldReturnAllByDefault() throws Exception {
    	mockMvc.perform(get("/rest/clubmember/"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].memberId", is(firstClubMember.getMemberId())))
        ;
    }
    
    @Test
    @WithMockUser(username="user", roles={"ADMIN"})
    public void listShouldReturnAllByDefaultWithoutTrailUrlSlash() throws Exception {
    	mockMvc.perform(get("/rest/clubmember"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].memberId", is(firstClubMember.getMemberId())))
        ;
    }
}