package com.schappet.c4.clubRoster.resouce;




import java.util.List;

import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Arrays;

import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.datatable.DataTableSearch;
import com.schappet.c4.clubRoster.dao.*;
import com.schappet.c4.clubRoster.domain.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.schappet.c4.clubRoster.controller.AbstractControllerMVCTests;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;

/**
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since Sat Apr 23 10:55:33 CDT 2016
 */
public class MemberGearResourceMvcTest extends AbstractControllerMVCTests {
	
    private MemberGear firstMemberGear;
    private ObjectMapper mapper;
    
    @Before
    public void before() { 
        // add 20 records to test database
        for(int x=1; x<21; x++){
        	MemberGear memberGear = new MemberGear();
        	clubRosterDaoService.getMemberGearService().save(memberGear);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstMemberGear = memberGear;
	        }
        }   
        this.mapper = new ObjectMapper();
        // fix NonUniqueObjectException
        this.clubRosterDaoService.getMemberGearService().getSession().flush();
        this.clubRosterDaoService.getMemberGearService().getSession().clear();
    }    
      
    @Test
    public void getByPathVariableIdShouldLoadAndReturnObject() throws Exception {
    	mockMvc.perform(get("null/membergear/"+firstMemberGear.getMemberGearId().toString()))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.memberGearId", is(firstMemberGear.getMemberGearId())))
        ;
    }
  
    @Test
    public void getByPathVariableIdShouldReturn404ForBogusId() throws Exception {
    	mockMvc.perform(get("null/membergear/-123")).andExpect(status().isNotFound()).andExpect(jsonPath("$.message", is("null/membergear/-123 could not be found.")));
    }
    
    @Test
    public void restMappingNotFoundShouldReturn404() throws Exception {
    	mockMvc.perform(get("null/membergear/asdfasdf/asdfasdf"))
    	.andExpect(status().isNotFound())
    	 .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.message", is("null/membergear/asdfasdf/asdfasdf could not be found.")))
    	;
    }
    
    @Test
    public void createShouldPersistAndReturnObject() throws Exception {
	   long count = clubRosterDaoService.getMemberGearService().count();	       
	   MemberGear memberGear = new MemberGear(); 
       
       mockMvc.perform(post("null/membergear/").content(this.mapper.writeValueAsString(memberGear))
	   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
	   .with(csrf()))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.memberGearId").value(IsNull.notNullValue()))  
       ;
       
       assertEquals("count should increase by 1", count +1 , clubRosterDaoService.getMemberGearService().count());
	}
     
    @Test
    public void updateShouldPersistExistingAndReturnObject() throws Exception {
       long count = clubRosterDaoService.getMemberGearService().count();

       mockMvc.perform(post("null/membergear/"+ firstMemberGear.getMemberGearId().toString())
    		   .content(this.mapper.writeValueAsString(firstMemberGear))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.memberGearId", is(firstMemberGear.getMemberGearId())))
       ;
         
       assertEquals("count NOT should increase", count , clubRosterDaoService.getMemberGearService().count());
  	}  
    
    @Test
    public void updateByPathVariableIdShouldReturn404ForMismatchBetweenPathIdAndObjectId() throws Exception {	       
       String correctId =  firstMemberGear.getMemberGearId().toString();
       // this ID manipulation should be overwritten with path variable id
       firstMemberGear.setMemberGearId(-123);
       
       mockMvc.perform(post("null/membergear/"+correctId)
    		   .content(this.mapper.writeValueAsString(firstMemberGear))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("null/membergear/" +correctId +" could not be found.")))
       ;
  	} 
    
    @Test
    public void updateByPathVariableIdShouldReturn404ForBogusPathId() throws Exception {
    	mockMvc.perform(post("null/membergear/-123")
    			.content(this.mapper.writeValueAsString(firstMemberGear))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
    	.andExpect(status().isNotFound())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	    .andExpect(jsonPath("$.message", is("null/membergear/-123 could not be found.")));
    }
    
    @Test
    public void deleteShouldDeleteAndReturnStatusOk() throws Exception {
        long count = clubRosterDaoService.getMemberGearService().count();

        mockMvc.perform(delete("null/membergear/"+ firstMemberGear.getMemberGearId().toString()).with(csrf()))
       .andExpect(status().isOk());  
       
       assertEquals("count should decrease by 1", count - 1 , clubRosterDaoService.getMemberGearService().count());
    }
    
    @Test
    public void deleteShouldFailWithBogusId() throws Exception {
        long count = clubRosterDaoService.getMemberGearService().count();

        mockMvc.perform(delete("null/membergear/-123").with(csrf()))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("null/membergear/-123 could not be found.")));  
       
       assertEquals("count should NOT decrease by 1", count , clubRosterDaoService.getMemberGearService().count());
    }

    @Test
    public void listShouldReturnAllByDefault() throws Exception {
    	mockMvc.perform(get("null/membergear/"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].memberGearId", is(firstMemberGear.getMemberGearId())))
        ;
    }
    
    @Test
    public void listShouldReturnAllByDefaultWithoutTrailUrlSlash() throws Exception {
    	mockMvc.perform(get("null/membergear"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].memberGearId", is(firstMemberGear.getMemberGearId())))
        ;
    }
}